---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: "```javascript function() {}```"
  checked: true
- value: ke
  checked: false
