---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Amazon
  checked: true
- value: Netflix
  checked: true
- value: Mumuki
  checked: true
