---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Opción 1
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Opción 2
  checked: true
name: Si todos lo podemos ver...
